CREATE TABLE [dbo].[Good]
(
	[Id] NVARCHAR(20) NOT NULL PRIMARY KEY,
	[CategoryId] NVARCHAR(15) NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	[Price] INT NOT NULL,
	[Quantity] INT NOT NULL,
	CONSTRAINT FK_GOOD_CATEGORY FOREIGN KEY (CategoryId) REFERENCES [dbo].[Category] (Id),
)
