CREATE TABLE [dbo].[OrderDetail]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[OrderId] INT NOT NULL,
	[GoodId] INT NOT NULL,
	[Quantity] INT NOT NULL,
	[IsDelivery] INT NOT NULL DEFAULT 0,
	CONSTRAINT FK_ORDERDETAIL_ORDER FOREIGN KEY ([OrderId]) REFERENCES [dbo].[Order] ([Id]),
	CONSTRAINT FK_ORDERDETAIL_GOOD FOREIGN KEY ([GoodId]) REFERENCES [dbo].[Good] ([Id]),
)
