CREATE TABLE [dbo].[Order]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[ClientId] INT NOT NULL,
	[ToTal] INT NOT NULL,
	CONSTRAINT FK_ORDERS_CLIENT FOREIGN KEY ([ClientId]) REFERENCES [dbo].[CLIENT] ([Id]),
)
